name: SellSigns
author: Piggyster
main: tk.piggyster.sellsigns.SellSignsPlugin
version: 1.5
depend: [ShopGUIPlus]
load: POSTWORLD
softdepend: [SkyblockPets, SuperiorSkyblock2]
commands:
  sellsigns:
    permission: sellsigns.admin
