name: SellSigns
author: Piggyster
main: tk.piggyster.sellsigns.SellSignsPlugin
version: 1.5
depend: [ShopGUIPlus]
load: POSTWORLD
loadbefore: [SkyblockPets]
commands:
  sellsigns:
    permission: sellsigns.admin
